name: Deploy Backend to Firebase Functions

on:
  push:
    branches: [ main ]
    paths: [ 'functions/**', 'firebase.json', 'firestore.*' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Install function dependencies
      working-directory: functions
      run: npm ci
      
    - name: Create Firebase service account key
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > firebase-service-account.json
        
    - name: Deploy to Firebase
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json
        firebase deploy --only functions,firestore:rules,storage
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Clean up
      if: always()
      run: rm -f firebase-service-account.json 